development:
  host: localhost
  database: mysociety_development

test:
  host: localhost
  database: mysociety_test

# set these environment variables on your prod server
production:
  host: localhost
  database: mysociety_production
